(defpackage cl-posix-mqueue.utils
  (:nicknames :mq.util)
  (:use :cl)
  (:export #:*errors*))
(in-package :cl-posix-mqueue.utils)

(defparameter *errors*
  '(2   no-file-or-directory
    4   interrupted-system-call
    9   bad-file-descriptor
    11  try-again
    12  out-of-memory
    13  access-denied
    17  file-exists
    22  invalid-argument
    24  too-many-open-files
    28  no-space-left-on-device
    36  name-too-long
    90  message-too-long
    110 connection-timed-out))
